core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.today, name='index'),
    path('today', views.today, name='today'),
    path('previous-day/', views.previous_day, name='previous-day'),
    path('next-day/', views.next_day, name='next-day'),
    path('memepage/', views.memepage, name='memepage'),
]

momepage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models


class Cohort(models.Model):
    """Model representing a Momentum cohort."""
    name = models.CharField(max_length=300,
                            help_text="Enter the name of the cohort here.")
    start_date = models.DateField(
        null=True,
        blank=True,
        help_text="Enter the start date for the cohort here.")
    end_date = models.DateField(
        null=True,
        blank=True,
        help_text="Enter the end date for the cohort here.")
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String for representing the Cohort object."""
        return self.name


class Day(models.Model):
    """Model representing a day of class for a Momentum cohort."""
    number = models.IntegerField(
        help_text="Enter the overall number of the day here.")
    week_number = models.IntegerField(
        help_text="Enter the number of the week here.")
    week_day_number = models.IntegerField(
        help_text="Enter the number of the day of the week here.")
    date = models.DateField(unique=True,
                            help_text="Enter the date of the day here.")
    description = models.TextField(
        null=True,
        blank=True,
        help_text="Enter the description of the day here.")
    created_date = models.DateTimeField(auto_now_add=True)

    # a Day belongs to one Cohort, and a Cohort will have many Days
    cohort = models.ForeignKey(Cohort, on_delete=models.CASCADE)

    def __str__(self):
        """String for representing the Day object."""
        return f"Day {self.number}"

    class Meta:
        ordering = ['-number']


class AgendaItem(models.Model):
    """Model representing an item on the agenda for a Day."""
    description = models.TextField(
        help_text="Enter the description of the agenda item here.")
    created_date = models.DateTimeField(auto_now_add=True)

    # an AgendaItem belongs to one Day, and a Day will have many AgendaItems
    day = models.ForeignKey(Day, on_delete=models.CASCADE)

    def __str__(self):
        """String for representing the AgendaItem object."""
        return self.description


class GuestLecture(models.Model):
    """Model representing a guest lecture for a Day."""
    start_time = models.TimeField(
        help_text="Enter the time when the guest lecture will start.")
    end_time = models.TimeField(
        help_text="Enter the time when the guest lecture will end.")
    speaker = models.CharField(
        max_length=300, help_text="Enter the name of the guest speaker here.")
    description = models.TextField(
        help_text="Enter the description of guest lecture here.")
    created_date = models.DateTimeField(auto_now_add=True)

    # an AgendaItem belongs to one Day, and a Day will have many AgendaItems
    day = models.ForeignKey(Day, on_delete=models.CASCADE)

    def __str__(self):
        """String for representing the GuestLecture object."""
        return f"{self.speaker} - {self.description}"


class FieldTrip(models.Model):
    """Model representing a field trip for a Day."""
    start_time = models.TimeField(
        help_text="Enter the time when the field trip will start.")
    end_time = models.TimeField(
        help_text="Enter the time when the field trip will end.")
    company = models.CharField(max_length=300,
                               help_text="Enter the name of the company here.")
    description = models.TextField(
        help_text="Enter the description of the field trip here.")
    created_date = models.DateTimeField(auto_now_add=True)

    # a FieldTrip belongs to one Day, and a Day will have many FieldTrips
    day = models.ForeignKey(Day, on_delete=models.CASCADE)

    def __str__(self):
        """String for representing the GuestLecture object."""
        return self.company


class Meme(models.Model):
    """Model for a simple img meme, only has a title and a url pointing to where the image is online"""
    meme_url = models.URLField(null=False)
    meme_title = models.CharField(max_length=100)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.meme_title

core/views.py
from django.shortcuts import render
from core.models import Cohort, Day, Meme
import datetime


def today(request):
    """
    View function for home page of site.
    The homepage currently displays Cohort 5's current day information.
    """
    previous_day_name = 'yesterday'
    next_day_name = 'tomorrow'
    day_name = '>today<'

    day = Day.objects.filter(date=datetime.date.today()).first()

    if is_Monday():
        previous_day_name = 'Friday'

    if is_Friday():
        next_day_name = 'Monday'

    return render(
        request, 'index.html', {
            'day': day,
            'dayName': day_name,
            'previousDayName': previous_day_name,
            'nextDayName': next_day_name,
        })


def is_Monday():
    """
    Returns true if it's Monday today
    """
    if datetime.date.today().weekday() == 0:
        return True
    else:
        return False


def is_Friday():
    """
    Returns true if it's Friday today
    """
    if datetime.date.today().weekday() == 4:
        return True
    else:
        return False


def previous_day(request):
    """
    View function for 'previous day' (usually yesterday) page of site, displaying the previous day's info.
    """
    previous_day_name = '>yesterday<'
    next_day_name = 'tomorrow'
    day_name = 'today'

    if is_Monday():
        previous_day_name = '>Friday<'

    if is_Friday():
        next_day_name = 'Monday'

    day = Day.objects.filter(date=datetime.date.today() -
                             datetime.timedelta(days=1)).first()
    return render(
        request, 'index.html', {
            'dayName': day_name,
            'previousDayName': previous_day_name,
            'nextDayName': next_day_name
        })


def next_day(request):
    """
    View function for 'next day' page of site (usually tomorrow), displaying the next day's info.
    """
    previous_day_name = 'yesterday'
    next_day_name = '>tomorrow<'
    day_name = 'today'

    if is_Monday():
        previous_day_name = 'Friday'

    if is_Friday():
        next_day_name = '>Monday<'

    day = Day.objects.filter(date=datetime.date.today() -
                             datetime.timedelta(days=1)).first()
    return render(
        request, 'index.html', {
            'dayName': day_name,
            'previousDayName': previous_day_name,
            'nextDayName': next_day_name
        })


def memepage(request):
    meme_list = Meme.objects.all().order_by('-date_added')
    return render(request, 'memepage.html', {
        'meme_list': meme_list,
    })

core/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block title %}<title>Momepage</title>{% endblock %}
</head>

<body>
    <h1>
        <a href="{% url 'memepage' %}">
            <img class="headerLogo" src="{% static 'img/header-logo.png' %}" alt="Momepage">
        </a>
    </h1>
    <nav class="day-navigation">
        <a href="{% url 'previous-day' %}">{{ previousDayName }}</a>
        <a href="{% url 'today' %}">{{ dayName }}</a>
        <a href="{% url 'next-day' %}">{{ nextDayName }}</a>
    </nav>
    {% block content %}
    {% endblock %}
</body>

</html>

core/templates/index.html
{% extends "base.html" %}

{% block title %}<title>Momepage - {{ day.date }}</title>{% endblock %}

{% block content %}
    <div class="index">
        <div class="today-header">
            <h2 class="today-header-number">
                Day {{ day.number }}
            </h2>
            <h2 class="today-week-and-day-numbers">
                Week {{ day.week_number }} - Day {{ day.week_day_number }}
            </h2>
            <h2 class="today-header-date">
                {{ day.date }}
            </h2>
        </div>
        <div class="today-agenda">
            <div class="today-description">
                {{ day.description }}
            </div>
            <div class="agenda-item-container">
                <h3>Agenda:</h3>
                {% for agenda_item in day.agendaitem_set.all %}
                    <div class="agenda-item">
                        {{ agenda_item.description }}
                    </div>
                {% endfor %}
            </div>
            <div class="guest-lecture-container">
                <h3>Guest Lectures:</h3>
                {% for guest_lecture in day.guestlecture_set.all %}
                    <div class="guest-lecture">
                        {{ guest_lecture.start_time }} - {{ guest_lecture.end_time }}:
                        <br>
                        {{ guest_lecture }}
                    </div>
                {% endfor %}
            </div>
            <div class="field-trip-container">
                <h3>Field Trips:</h3>
                {% for field_trip in day.fieldtrip_set.all %}
                    <div class="field-trip">
                        {{ field_trip.start_time }} - {{ field_trip.end_time }}:
                        <br>
                        {{ field_trip.company }}
                        <br>
                        {{ field_trip.description }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

core/templates/memepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Memepage</title>
</head>

<body>
    <header>
        <h1>
            <a href="{% url 'index' %}">
                <img class="headerLogo" src="{% static 'img/meme-header-logo.png' %}" alt="Memepage">
            </a>
        </h1>
    </header>
    <main class="meme-main">
        <ul class="meme-ul">
            {% for meme in meme_list %}
            <li class="meme-li">
                <img class="meme-img" src="{{meme.meme_url}}">
                <br>
                <h3>{{meme.meme_title}}</h3>
            </li>
            {% endfor %}
        </ul>
    </main>
</body>

</html>